apiVersion: apps/v1
kind: Deployment
metadata:
name: hellotest
labels:
  app: hellotest
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hellotest
      tier: hellotest
  spec:
    containers:
      - name: hellotest
        image: gcr.io/testpipeline20200709/hellotest:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: hello

---
apiVersion: v1
kind: Service
metadata:
name: hellotest
labels:
  app: hellotest
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: hellotest
  tier: hellotest
type: LoadBalancer