apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellotest
  labels:
    app: hellotest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellotest
  template:
    metadata:
      labels:
        app: hellotest
    spec:
      containers:
        - name: hellotest
          image: gcr.io/testci20200723/hellotest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: hellotest
  labels:
    app: hellotest
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: hellotest
  type: LoadBalancer